// Not subject to change, so hardcoded for better type-checking
export enum ECourse {
  maths = "MATHS",
  francais = "FRANCAIS",
  anglais = "ANGLAIS",
  espagnol = "ESPAGNOL",
  allemand = "ALLEMAND",
  italien = "ITALIEN",
  portugais = "PORTUGAIS",
  arabe = "ARABE",
  latin = "LATIN",
  grecAncien = "GREC ANCIEN",
  histoire = "HISTOIRE",
  geographie = "GEOGRAPHIE",
  educationCivique = "EDUCATION CIVIQUE",
  philosophie = "PHILOSOPHIE",
  educationMusicale = "EDUCATION MUSICALE",
  artsPlastiques = "ARTS PLASTIQUES",
  sciencesDeLaVieEtDeLaTerre = "SCIENCES DE LA VIE ET DE LA TERRE",
  sciencesPhysiquesEtChimie = "SCIENCES PHYSIQUES ET CHIMIE",
  technologie = "TECHNOLOGIE",
  droit = "DROIT",
  sciencesEconomiquesEtSociales = "SCIENCES ECONOMIQUES ET SOCIALES",
  gestion = "GESTION",
  educationPhysiqueEtSportive = "EDUCATION PHYSIQUE ET SPORTIVE",
  educationReligieuse = "EDUCATION RELIGIEUSE",
}
