import { EGrade } from './grade.enum';
import { ESubject } from './subject.enum';
import { ObjectId } from 'bson';

/**
 * Used for authentication and sign-up
 */
export interface IUserAuth {
  email: string,
  password: string, // to be removed outside of auth
  firstName?: string;
  lastName?: string;
}

/**
 * **All** data about a user.
 * @property {ObjectId} _id autogenerated in database
 * @property {string} email
 * @property {string} firstName
 * @property {string} lastName
 * @property {File} avatar
 * @property {Date} joinDate
 * @property {string} description
 * @property {string} location
 * @property {EGrade[]} grades
 * @property {ESubject[]} subjects
 * @property {ObjectId[]} postIds
 * @property {ObjectId[]} bookmarkIds
 * @property {ObjectId[]} commentIds
 */
export interface IUserDB extends IUserAuth {
  _id?: ObjectId;
  avatar?: File;
  joinDate: Date;
  description: string;
  location: string;
  grades: EGrade[];
  subjects: ESubject[];
  // foreign keys
  lessonIds: ObjectId[];
  bookmarkIds: ObjectId[];
  commentIds: ObjectId[];
}

/**
 * Used for sending data to the client about a User
 */
export type IUserPublic = Omit<IUserDB, 'password'>;
